<Project>
    <PropertyGroup>
        <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    </PropertyGroup>

    <PropertyGroup>
        <IsWebApplicationProject Condition="$(ProjectTypeGuids.Contains('{349c5851-65df-11da-9384-00065b846f21}'))">true</IsWebApplicationProject>
    </PropertyGroup>

    <Import Project="$(MSBuildThisFileDirectory)Cogito.AspNet.MSBuild.Tasks.targets" />
    <Import Project="$(MSBuildThisFileDirectory)AssemblyBindingRedirects.targets" />
    <Import Project="$(MSBuildThisFileDirectory)WebProjectReference.targets" />

</Project>
